#!/bin/bash
SESSION=`basename $PWD`

tmux -2 new-session -d -s $SESSION
tmux rename-window -t $SESSION:1 "vim main"
tm-3
tm-rv

tmux new-window -t $SESSION -a -n ops
tmux split-window -v
tm-rv

tmux select-window -t $SESSION:1
tmux -2 attach -t $SESSION
